name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        
    - name: Verify repository structure
      run: |
        Write-Host "Verifying basic repository structure..."
        $requiredFiles = @(
          "package.json",
          "README.md"
        )
        
        foreach ($file in $requiredFiles) {
          if (!(Test-Path $file)) {
            throw "$file not found"
          } else {
            Write-Host "$file ✓"
          }
        }
        
        Write-Host "Repository structure verification completed successfully!"
      shell: pwsh 